site_name: Architecture Docs
site_url: https://vishnu-staples.github.io/architecture-doc-repo/

theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 1-3
  - attr_list

use_directory_urls: false

extra_css:
  - styles/extra.css

plugins:
  - search
  - mermaid2
  - glightbox